# Generated by Django 4.2.3 on 2023-07-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='image_url',
            field=models.TextField(null=True),
        ),
    ]
